### ISSUE TITLE
Error on adding field craft 4

### ISSUE THREAD

**Issue by maartenheideman** [oberonamsterdam/craft-starfield#4]
When I'll try to add a starfield I'll get an error: `Calling unknown method: craft\web\View::renderTemplateMacro()`.

 in...vendor/craftcms/cms/src/templates/settings/fields/_type-settings.twig at line 2

{% namespace namespace ?? null %}
    {{ field.getSettingsHtml()|raw }}
{% endnamespace %}

**Comment by redboer** [comment]
Resolved in 2.1.1. Thanks!
